version: '3'

services:
  plin_api_inadimplencia:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: plin_api_inadimplencia
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/home/node/app

